version: '3'

services:
  web:
    build: .
    container_name: blog_tz
    command: gunicorn blog_tz.wsgi
    volumes:
      - .:/blog_tz/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A blog_tz worker -B
    volumes:
      - .:/blog_tz/
    links:
      - redis
    depends_on:
      - web
      - redis
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/blog_tz/

  redis:
    image: redis