version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery:
    restart: always
    build: .
    command: celery -A blog_tz worker -l INFO --pool=solo
    volumes:
      - ./:/usr/src/app
    depends_on:
      - web
      - redis
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis

volumes:
  pgdata: